services:
  webtop:
    image: lscr.io/linuxserver/webtop:ubuntu-xfce
    container_name: webtop2
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Indochina/Bangkok
      - SUBFOLDER=/ # optional
      - TITLE=Webtop # optional
    volumes:
      - webtop_config:/config
    ports:
      - 3000:3000
      - 3001:3001
    shm_size: "256m" # optional
    restart: unless-stopped

volumes:
  webtop_config:
